name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future && find /srv/jekyll/_site -type f -name '*.html' -exec xmllint --noout {} \; && wget https://github.com/validator/validator/releases/download/18.11.5/vnu.jar_18.11.5.zip && unzip -p vnu.jar_18.11.5.zip dist/vnu.jar > vnu.jar && java -jar vnu.jar --skip-non-html /srv/jekyll/_site"
